name: Screener build

on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [labeled]
env:
  DEPLOYHOST: 'fluentuipr.z22.web.core.windows.net'
jobs:
  comment-trigger:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Run VR tests' && github.event.issue.pull_request
    steps:
      - name: Get PR info
        uses: actions/github-script@v6
        with:
          script: |
            let PR = await github.rest.pulls.get({
              pull_number: ${{github.event.issue.number}},
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.exportVariable('SYSTEM_PULLREQUEST_TARGETBRANCH', PR.data.base.ref);
            core.exportVariable('SYSTEM_PULLREQUEST_SOURCEBRANCH', PR.data.head.ref);
            core.exportVariable('SYSTEM_PULLREQUEST_PULLREQUESTID', PR.data.id);
            core.exportVariable('SYSTEM_PULLREQUEST_SOURCECOMMITID', PR.data.head.sha);
      ###########################################
      # SYSTEM_PULLREQUEST_TARGETBRANCH = target branch name
      # SYSTEM_PULLREQUEST_SOURCEBRANCH = source branch name
      # SYSTEM_PULLREQUEST_PULLREQUESTID = ID of the PR
      # SYSTEM_PULLREQUEST_SOURCECOMMITID = commit SHA of PR
      # DEPLOYBASEPATH = path for deploy URL -> pull/<pr_number> for PRs
      # DEPLOYURL= address for tests deployment, uses DEPLOYHOST and DEPLOYBASEPATH
      # BUILD_SOURCEBRANCHNAME = 'merge' for PRs
      ###########################################
      - name: Set env variables
        run: |
          cat <<EOT >> environment
          SYSTEM_PULLREQUEST_TARGETBRANCH=${{ env.SYSTEM_PULLREQUEST_TARGETBRANCH }}
          SYSTEM_PULLREQUEST_SOURCEBRANCH=${{ env.SYSTEM_PULLREQUEST_SOURCEBRANCH }}
          SYSTEM_PULLREQUEST_PULLREQUESTID=${{ env.SYSTEM_PULLREQUEST_PULLREQUESTID }}
          SYSTEM_PULLREQUEST_SOURCECOMMITID=${{ env.SYSTEM_PULLREQUEST_SOURCECOMMITID }}
          DEPLOYHOST=${{ env.DEPLOYHOST }}
          DEPLOYBASEPATH=pull/${{env.PR_NUMBER}}
          DEPLOYURL=https://${{env.DEPLOYHOST}}/pull/${{env.PR_NUMBER}}
          EOT

      ###########################################
      # BROWSERSLIST_IGNORE_OLD_DATA = Prevents failures on CI when "caniuse-lite" becomes outdated
      # DEPLOYHOST = address of host for screener tests deployment
      # BUILD_BUILDID = unique ID of the workflow run within the repo
      # BUILD_SOURCEBRANCH = branch that triggered the workflow -> refs/pull/<pr_number>/merge
      ###########################################
      - name: Set base env variables
        run: |
          cat <<EOT >> environment
          BROWSERSLIST_IGNORE_OLD_DATA=true
          DEPLOYHOST='fluentuipr.z22.web.core.windows.net'
          BUILD_BUILDID=${{ github.run_id }}
          BUILD_SOURCEBRANCH=${{ github.ref }}
          SCREENER_BUILD=1
          EOT

      - uses: actions/upload-artifact@v2
        with:
          name: env-artifact
          path: environment

      - run: |
          printenv | sort

      - name: script_label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{github.event.issue.number}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Ready for VR']
            })
  push-trigger:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set base env variables
        run: |
          cat <<EOT >> environment
          BROWSERSLIST_IGNORE_OLD_DATA=true
          DEPLOYHOST='fluentuipr.z22.web.core.windows.net'
          BUILD_BUILDID=${{ github.run_id }}
          BUILD_SOURCEBRANCH=${{ github.ref }}
          SCREENER_BUILD=1
          EOT
      - name: Set env variables for master builds
        run: |
          cat <<EOT >> environment
          DEPLOYBASEPATH=heads/${{github.ref_name}}
          DEPLOYURL=https://${{env.DEPLOYHOST}}/heads/${{github.ref_name}}
          BUILD_SOURCEBRANCHNAME=${{ github.ref_name }}
          EOT
      - uses: actions/upload-artifact@v2
        with:
          name: env-artifact
          path: environment
  label-trigger:
    if: ${{github.event.label.name == 'Ready for VR'}}
    runs-on: ubuntu-latest
    steps:
      - name: Set base env variables
        run: |
          cat <<EOT >> environment
          BROWSERSLIST_IGNORE_OLD_DATA=true
          DEPLOYHOST='fluentuipr.z22.web.core.windows.net'
          BUILD_BUILDID=${{ github.run_id }}
          BUILD_SOURCEBRANCH=${{ github.ref }}
          SCREENER_BUILD=1
          EOT
      - name: Set env variables if there is a PR
        run: |
          cat <<EOT >> environment
          SYSTEM_PULLREQUEST_TARGETBRANCH=${{ github.event.pull_request.base.ref }}
          SYSTEM_PULLREQUEST_SOURCEBRANCH=${{ github.event.pull_request.head.ref }}
          SYSTEM_PULLREQUEST_PULLREQUESTID=${{ github.event.pull_request.id }}
          SYSTEM_PULLREQUEST_SOURCECOMMITID=${{ github.event.pull_request.head.sha }}
          DEPLOYBASEPATH=pull/${{github.event.pull_request.number}}
          DEPLOYURL=https://${{env.DEPLOYHOST}}/pull/${{github.event.pull_request.number}}
          BUILD_SOURCEBRANCHNAME='merge'
          EOT
      - uses: actions/upload-artifact@v2
        with:
          name: env-artifact
          path: environment

  screener-react-northstar:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success')}}
    needs: [comment-trigger, push-trigger, label-trigger]
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react-northstar
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download env variables artifact
        uses: actions/download-artifact@v3
        with:
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/docs --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if northstar packages were affected

      - run: |
          yarn lage info --since origin/master
        name: Log affected packages (debug)
        if: ${{startsWith(github.ref, 'refs/pull/')}}

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build FUI N* VR Test
        run: yarn workspace @fluentui/docs vr:build
        env:
          SCREENER_BUILD: 1
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: northstar-artifact
          path: packages/fluentui/docs/dist
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

  screener-react:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success')}}
    needs: [comment-trigger, push-trigger, label-trigger]
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download env variables artifact
        uses: actions/download-artifact@v3
        with:
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/vr-tests --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if v8 packages were affected

      - run: |
          yarn lage info --since origin/master
        name: Log affected packages (debug)
        if: ${{startsWith(github.ref, 'refs/pull/')}}

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build vr-tests storybook
        run: yarn workspace @fluentui/vr-tests screener:build
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: screener-artifact
          path: apps/vr-tests/dist/storybook
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

  screener-react-components:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success')}}
    needs: [comment-trigger, push-trigger, label-trigger]
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react-components
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download env variables artifact
        uses: actions/download-artifact@v3
        with:
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/vr-tests-react-components --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if v9 packages were affected

      - run: |
          yarn lage info --since origin/master
        name: Log affected packages (debug)
        if: ${{startsWith(github.ref, 'refs/pull/')}}

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build vr-tests-react-components storybook
        run: yarn workspace @fluentui/vr-tests-react-components screener:build
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: vnext-artifact
          path: apps/vr-tests-react-components/dist/storybook
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}
