name: Screener build

on:
  workflow_run:
    workflows:
      - Create label
    types:
      - completed

jobs:
  send-workflow-run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "RUN_ID=${{github.event.workflow_run.id}}" >> run-id
      - uses: actions/upload-artifact@v2
        with:
          name: run-id
          path: run-id
  screener-react-northstar:
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react-northstar
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download environment variables artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-label.yml
          run_id: ${{github.event.workflow_run.id}}
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/docs --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if northstar packages were affected

      - run: |
          yarn lage info --since origin/master
        name: Log affected packages (debug)
        if: ${{startsWith(github.ref, 'refs/pull/')}}

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build FUI N* VR Test
        run: yarn workspace @fluentui/docs vr:build
        env:
          SCREENER_BUILD: 1
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: northstar-artifact
          path: packages/fluentui/docs/dist
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

  screener-react:
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download environment variables artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-label.yml
          run_id: ${{github.event.workflow_run.id}}
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/vr-tests --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if v8 packages were affected

      - run: |
          yarn lage info --since origin/master
        name: Log affected packages (debug)
        if: ${{startsWith(github.ref, 'refs/pull/')}}

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build vr-tests storybook
        run: yarn workspace @fluentui/vr-tests screener:build
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: screener-artifact
          path: apps/vr-tests/dist/storybook
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

  screener-react-components:
    runs-on: 'ubuntu-latest'
    name: Screener @fluentui/react-components
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download environment variables artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-label.yml
          run_id: ${{github.event.workflow_run.id}}
          name: env-artifact

      - name: Define env variables
        run: |
          input_file="environment"
          while read line
          do
          echo "$line" >> $GITHUB_ENV
          done < "$input_file"

      - name: Delete environment file
        run: |
          rm environment

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          echo "Is PR build? ${{startsWith(github.ref, 'refs/pull/')}}"
          packageAffected=$(yarn --silent check:affected-package --packages @fluentui/vr-tests-react-components --pr=${{startsWith(github.ref, 'refs/pull/')}})
          if [[ $packageAffected == false ]]; then
            echo "Should skip screener"
            echo "SKIP_SCREENER_BUILD=true" >> $GITHUB_ENV
          else
            echo "SKIP_SCREENER_BUILD=false" >> $GITHUB_ENV
            echo "Should NOT skip screener"
          fi
        name: Check if v9 packages were affected

      - run: |
          yarn lage info --since origin/master
        name: Log affected packages (debug)
        if: ${{startsWith(github.ref, 'refs/pull/')}}

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: build vr-tests-react-components storybook
        run: yarn workspace @fluentui/vr-tests-react-components screener:build
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}

      - uses: actions/upload-artifact@v3
        with:
          name: vnext-artifact
          path: apps/vr-tests-react-components/dist/storybook
        if: ${{env.SKIP_SCREENER_BUILD == 'false'}}
